[package]
name = "item_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
item_macro = { path = "item_macro" }

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"