[package]
name = "gomoku_term"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gomoku_util = { path = "../gomoku_util" }
crossterm = "0.23.2"
