[package]
name = "item_macro"
version = "0.1.0"
edition = "2021"

[lib]
name = "item_macro"
path = "lib.rs"
proc-macro = true

[dependencies]
quote = "1.0.10"
syn = { version = "1.0.81", features = ["extra-traits"] }