[package]
name = "webapp_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.2.1"
anyhow = "1.0.68"
diesel = { version = "2.0.2", features = ["sqlite"] }
dotenv = "0.15.0"
